# Generated by Django 4.2.16 on 2026-02-03 09:48

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pics',
            field=models.FileField(blank=True, null=True, upload_to=account.models.upload_to),
        ),
    ]
